Repository tenacityteam/tenacity, pull requests merged in 2021-08, with the labels that each got.

#427 Fix AboutDialog
  src/AboutDialog.cpp
Labels: bug, build

#461 Convert issue templates to forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: enhancement

#465 Use Tenacity.Project in AudacityApp.cpp
  src/AudacityApp.cpp
Labels: windows testing wanted, macos testing wanted

#483 Fixed Audacity.Project regression, added own branding
  src/AudacityApp.cpp
Labels: high priority

#528 BUILDING.md: Add PortSMF Debian build instructions
  BUILDING.md
Labels: needs-additional-review
