Repository tenacityteam/tenacity, pull requests merged in 2021-07, with the labels that each got.

#198 Reattempt fixing MacOS build problem related to CPack issue
  mac/scripts/build_dist.sh
  scripts/ci/macos/repeat_hdiutil.sh
  scripts/ci/package.sh
Labels: bug, build

#295 Fix incorrect AudacityCommand's PluginTypeString
  src/PluginManager.cpp
Labels: high priority

#302 🐛 Fixed missing files when packaging with ninja on windows
  CMakeLists.txt
  help/CMakeLists.txt
  images/CMakeLists.txt
  locale/CMakeLists.txt
  modules/CMakeLists.txt
  nyquist/CMakeLists.txt
  plug-ins/CMakeLists.txt
  src/CMakeLists.txt
Labels: windows testing wanted

#342 Add solid fill in icons to improve visibility
  images/AudacityLogoAlpha.xpm
  images/icons/16x16/tenacity.png
  images/icons/16x16/tenacity16.xpm
  images/icons/22x22/tenacity.png
  images/icons/24x24/tenacity.png
  images/icons/32x32/tenacity.png
  images/icons/32x32/tenacity32.xpm
  images/icons/48x48/tenacity.png
  images/icons/48x48/tenacity.xpm
  images/tenacity.svg
Labels: enhancement

#334 Correct MacOS CPack configuration
  scripts/ci/macos/repeat_hdiutil.sh
  scripts/ci/package.sh
Labels: bug, build

#378 Change configuration and data directories
  src/AboutDialog.cpp
  src/AudacityApp.cpp
  src/FileNames.cpp
  src/FileNames.h
Labels: macos testing wanted

#327 Add hiDPI support for Windows
  win/Tenacity.exe.manifest
Labels: bug, high priority

#418 Fix memory leak from `alloca` fix
  src/AudioIO.cpp
  src/AudioIO.h
  src/AudioIOBufferHelper.h
  src/CMakeLists.txt
Labels: bug, high priority

#417 Fix for unsafe `char*` to `wchar_t*` cast (CWE-704)
  src/ProjectSerializer.cpp
Labels: linux testing wanted, macos testing wanted
