Repository tenacityteam/tenacity, pull requests merged in 2021-09, with the labels that each got.

#300 Restore compatibility with wxWidgets-3.0
  BUILDING.md
  CMakeLists.txt
  libraries/lib-strings/TranslatableString.cpp
  src/AudacityApp.cpp
  src/FileNames.cpp
Labels: high priority

#634 Make wxWidgets version in About dialog more visible
  src/AboutDialog.cpp
  src/BuildInfo.h
Labels: windows testing wanted, macos testing wanted

#632 Tenacity renaming in macOS manifest
  cmake-proxies/cmake-modules/MacOSXBundleInfo.plist.in
Labels: macos testing wanted, needs additional review

#402 ControlToolBar: Reorder icons
  src/toolbars/ControlToolBar.cpp
  src/toolbars/ControlToolBar.h
Labels: design

#642 Rename freedesktop and metainfo files to reverse DNS schema
  help/CMakeLists.txt
  help/org.tenacityaudio.Tenacity.metainfo.xml
  packaging/flatpak/org.tenacity.Tenacity.json
  src/CMakeLists.txt
  src/org.tenacityaudio.Tenacity.desktop.in
  src/org.tenacityaudio.Tenacity.xml
Labels: needs additional review
